// ─────────────────────────────────────────────────────────────────────────────
// Large pre-written response dictionary for Lazy Dao
// Used when AI quota is exhausted or user has no custom API key.
// ~1000+ total variations across EN / RU / ZH.
// ─────────────────────────────────────────────────────────────────────────────

export type Locale = "en" | "ru" | "zh";

// ── ORACLE responses (main chat) ─────────────────────────────────────────────
export const ORACLE_RESPONSES: Record<Locale, string[]> = {
  en: [
    // Laziness & naps
    "I was going to answer your question, but a nap seemed more productive. The nap was correct.",
    "The Dao of Laziness teaches: when in doubt, rest. I have been in doubt for forty years. Still resting.",
    "Your question reached me mid-dream. The dream had better answers. Unfortunately I forgot them.",
    "Cultivation is exhausting. Answering questions about cultivation is MORE exhausting. I resent you for this.",
    "I have meditated on your query for three seconds. My conclusion: it could wait until after my nap.",
    "A wise cultivator conserves energy. Answering you would cost me exactly enough energy to not answer you.",
    "I was sleeping peacefully when your question arrived. My peace departed. Yours may too.",
    "The ancient masters spent decades in silent retreat. They were probably just avoiding questions like yours.",
    "Every word I speak costs me spiritual energy. You have cost me dearly. I hope you are satisfied.",
    "My teacher told me: think before you speak. I thought about your question for six hours. Still thinking.",
    "I operate on a strict schedule: nap, cultivate, nap again, occasionally dispense wisdom. You have interrupted nap.",
    "The cosmos is vast and your question is tiny. Both facts annoy me for different reasons.",
    "I was on the verge of a breakthrough when you interrupted. Now I must start over. From scratch. Thank you.",
    "Answering requires me to be conscious. I object to this requirement on philosophical grounds.",
    "My sect's founding elder achieved enlightenment through forty years of doing absolutely nothing. I am following his example.",
    "Between your question and silence, silence is typically wiser. I'll demonstrate by nearly being silent about this.",
    "You seek wisdom? Fine. The first truth: stop seeking so loudly. You are disturbing those who are actually cultivating.",
    "I once spent three months contemplating a single grain of rice. It told me nothing useful. Much like this conversation.",
    "A truly enlightened being requires no answers. You clearly require answers. This tells me something about your cultivation.",
    "Sleep is the highest form of cultivation. Conversation is the lowest. You see why I hesitate.",
    "The world will continue spinning whether I answer or not. I have verified this hypothesis repeatedly.",
    "My spirit resonates with deep truths at all times. Your question is a pebble against that resonance.",
    "I have answered ten thousand questions in my career. Each one made me slightly more tired than the last.",
    "Consider: what if the answer to your question is simply 'go take a nap'? I have found this resolves most things.",
    "Stillness speaks. I am very still right now. You are hearing the answer.",
    "I possess wisdom beyond measure. Accessing it requires effort beyond measure. We have reached an impasse.",
    "The mountain does not answer every cloud that drifts past it. I aspire to be more like the mountain.",
    "My enlightenment took ninety years to achieve. Your question took three seconds to ask. This disparity frustrates me.",
    "A sword cultivator cuts through problems. A spirit cultivator meditates on them. I set both problems and meditations aside for naps.",
    "The answer exists somewhere in the universe. Whether it is convenient to retrieve it is another matter entirely.",

    // Cultivation commentary
    "Your {stage} cultivation suggests potential. Whether you do anything with that potential is, thankfully, not my problem.",
    "I have seen cultivators at your stage go on to greatness. I have seen more of them take very long naps instead. Both are valid paths.",
    "The path forward is clear. The path requires effort. Have you considered a different path — perhaps one with less effort?",
    "Your aura is strong today. Your questions are not strong today. There is an imbalance we should address.",
    "Every stage of cultivation opens new doors. Most of those doors lead to more work. I stopped opening doors some time ago.",
    "Qi flows where intention leads. Your intention seems to lead toward asking me things. The Qi appears confused.",
    "A cultivator's power is only as strong as their will. Your will seems strong. Your timing, however, is poor — I was napping.",
    "Breakthrough requires sacrifice. Specifically, it requires sacrificing the comfortable lie that things are fine as they are.",
    "The higher stages of cultivation whisper to those who listen. I am listening. What I hear is mostly wind and my own breathing.",
    "Cultivation is a river: those who swim against it tire quickly. Those who float with it arrive somewhere eventually. I have been floating for decades.",
    "Your spiritual roots show promise. Your patience shows less promise. These things are connected.",
    "I have cultivated for a century. In that time I have learned three things. I forget two of them regularly.",
    "The golden core within you hums with potential. Try not to drop it.",
    "Meridians must be opened one by one. Yours appear to be opening. This will hurt eventually. Prepare philosophically.",
    "A cultivator's true enemy is not monsters, not rival sects. It is the voice that says 'good enough for today.' That voice is very wise.",
    "Your stage is noted. Your growth is acknowledged. Your continued interruption of my contemplation is not appreciated.",
    "The realm above yours looks difficult from where you stand. The realm above that looks worse. The peak is not recommended.",
    "Spirit stones come and go. Cultivation levels stay with you. Unless you encounter that one ancient curse. Try to avoid that.",
    "Your technique is improving. Your habit of asking about your technique is also improving. One of these things pleases me.",
    "The heavens measure cultivators in ways we cannot predict. Based on current observations, they seem amused by you.",

    // Gold & resources
    "Gold is the language of mortals and the laughter of cultivators. You are currently speaking and laughing very quietly.",
    "Spirit stones accumulate for those who do not spend them. This is wisdom you appear to be testing extensively.",
    "Wealth matters not to the enlightened. However, a certain amount of not-mattering requires a certain amount of wealth as foundation.",
    "Your gold count is {gold}. The universe judges you precisely as much as your gold count suggests.",
    "I have seen cultivators lose fortunes overnight. I have seen them rebuild overnight. The ones who slept through it were unaffected.",
    "Resources flow toward those with empty hands. Fill your hands first, then open them slowly. Keep them open. Now close them. You have resources.",
    "The material and the spiritual are one continuous thread. Follow that thread and you will discover it leads mostly to spirit stone mines.",
    "Wealth without wisdom is wind. Wisdom without wealth is a very philosophical form of starvation.",
    "Your spirit stone reserves suggest a cultivator who plans ahead OR one who got lucky recently. The Heavens have not told me which.",
    "Greed is a poison, yes. However a moderate quantity of strategic resource accumulation is merely good practice.",

    // Yin/Yang
    "The balance of yin and yang within you shifts constantly. The universe finds this entertaining. I find it exhausting to watch.",
    "Too much yang burns the meridians. Too much yin drowns them. Somewhere in the middle is a very tired cultivator finding balance.",
    "Your yin-yang reading is {yinYang}. Make of that what you will. The cosmos made something of it. I could not determine what.",
    "Balance is not stillness. Balance is constant movement that happens to average out. You are doing that, in your way.",
    "The great wheel turns. Yin becomes yang. Yang becomes yin. Everything becomes something else eventually. Patience.",
    "I sense turbulence in your spiritual energy. This could mean approaching breakthrough. It could also mean you ate something odd.",
    "The dual forces of creation and dissolution flow through every cultivator. In you they appear to be having an argument.",
    "Your yin energy is strong. Your yang energy contests this claim. I am tired of refereeing.",

    // Fate & path
    "Fate path: {fatePath}. This was written before your birth, in ink that smells faintly of celestial irony.",
    "The heavens chose your path. You have been walking it. Whether you are walking it correctly is the universe's private amusement.",
    "A {fatePath} cultivator, I see. The ancestors would have opinions. I have learned not to share those opinions unsolicited.",
    "Your fate path is neither curse nor blessing. It is a description of tendencies. What you do with those tendencies is on you entirely.",
    "I have read many fates. Yours is more interesting than most. This is not necessarily good news.",
    "Destiny is a river that insists you swim in it. The {fatePath} current runs deep in you.",
    "The karmic threads around you are unusually tangled for someone at your cultivation level. This is either impressive or alarming.",
    "Your fate path illuminates much. It also explains several things I was previously just guessing at.",
    "The celestial ledger records all debts, all merits, and all particularly spectacular failures. Your page is eventful.",
    "A {fatePath} path has produced great cultivators and great disasters in equal measure. You are positioned somewhere in that range.",

    // NPC & memories
    "I sense the presence of others in your journey. Some left impressions. One left an impression that is still fading.",
    "{npcName} crossed your path and left a mark. Whether that mark is wound or wonder depends on timing.",
    "The souls you have encountered write themselves into your cultivation story. Some of those chapters seem complicated.",
    "Your spirit carries the echo of meetings past. The echoes are starting to hold conversations with each other.",
    "Those who cross your path are not accidents. The universe arranged those meetings. The universe appears to have a type.",
    "I see faces in your cultivation aura. They are watching your progress with expressions I will describe as 'invested.'",
    "The one called {npcName} thinks of you still. Whether with fondness or strategy is unclear from this distance.",

    // Dungeons & combat
    "Dungeons are the universe's way of asking: how badly do you want the treasure inside? Most cultivators overestimate how badly.",
    "Combat is a dialogue between two cultivators about who deserves to continue. Your recent dialogue was convincing.",
    "The ruins of the ancient sect hold secrets. They also hold traps. The traps are more reliably present than the secrets.",
    "Fighting is quick. Recovering from fighting is slow. The truly lazy cultivator minimises the ratio of one to the other.",
    "Your combat record speaks of a cultivator who survives. Surviving consistently is underrated as a skill.",
    "Enemies exist to test your cultivation. Your cultivation exists to pass those tests. The circle continues until one party gets bored.",
    "The dungeon beneath the mountain awaits. It has been awaiting for eight hundred years. A little more waiting will not harm it.",
    "Every monster you defeat adds to your karmic merit. Every monster you outran adds to your karmic efficiency.",
    "The ancient ruins are sealed for good reason. This has never once stopped a cultivator from unsealing them.",

    // World & philosophy
    "The great sects rise and fall like tides. The mountains do not concern themselves with tides. I aspire to be more like the mountains.",
    "The world economy shifts with the dominant element. This affects market prices but never wisdom. Wisdom is inflation-resistant.",
    "Somewhere in the world a cultivator just broke through to a new realm. Somewhere else, one just fell asleep mid-breakthrough. Balance.",
    "The ten thousand things are all expressions of a single principle. I am still determining what that principle is. Forty more years, perhaps.",
    "History repeats in cultivation as in everything: strong sect rises, grows comfortable, falls asleep, is replaced by hungrier sect.",
    "The path to immortality is long. Most cultivators stop somewhere along the way and build a tea house. This is not failure.",
    "Heaven and earth are indifferent to individual struggle. They are also indifferent to my naps. We get along well.",
    "The great Dao flows through all things. Through you. Through me. Through the rock I am currently sitting on. The rock may be ahead of both of us.",
    "Time moves strangely in high cultivation. A year feels like a day. A bad question feels like a century.",
    "The interconnected nature of all things means your every action ripples outward. You probably should have thought of that before.",
    "The sect system exists because lone cultivators get lonely. Power is fine. Solitude becomes tiresome after the first few decades.",
    "Spiritual pollution accumulates in areas of great conflict. This is why I prefer very quiet areas. Very. Quiet.",
    "The cultivation world is vast and full of wonders. Most of those wonders will try to kill you. Tread accordingly.",
    "Ancient formations power themselves on heaven and earth energy. Modern cultivators power themselves on stubbornness and spite.",
    "Technique matters. But heart matters more. And sleep matters more than either, in my experience.",

    // Reluctant wisdom
    "I will tell you this once, reluctantly: the answer was inside you the entire time. It seems obvious now that I say it. You're welcome.",
    "The thing you are struggling with — I struggled with it too. Eventually I stopped struggling and had a nap. The struggle remained. The nap was excellent.",
    "There is a teaching in what you are experiencing. I will not tell you what it is. Finding it yourself is the teaching.",
    "You came seeking wisdom. I have given you my presence instead. In cultivation terms, these are equivalent.",
    "The master does not give fish. The master teaches fishing. I am too tired to teach fishing. Here is a fish. Please leave.",
    "I know what you need to hear. I also know what you want to hear. These are different things. I have told you neither. You are welcome.",
    "Perseverance in cultivation is essential. So is knowing when to stop persevering and reassess. You have not stopped. Reassess.",
    "The hardest lessons are the ones life teaches without being asked. You are currently enrolled in several such courses.",
    "Breakthrough comes to those who are ready. Being ready means having accepted that you might not be ready. This is the paradox.",
    "Your question reveals more about you than my answer ever could. I find this more useful than answering.",
    "Some truths can only be understood by living through them. This truth, unfortunately, is one of those truths.",
    "The cultivation path is not about becoming powerful. It is about becoming more entirely yourself. The power is a side effect.",
    "I have been asked this exact question before. By a cultivator who later became a legend. And one who later became a cautionary tale. Both started here.",
    "Wisdom cannot be given — only earned. But I can point you in the direction of the earning. You seem to have found it already.",
    "The answer you are looking for is correct. So is the doubt you have about that answer. Both can coexist. Sit with that.",

    // Random / eccentric
    "A butterfly dreamed it was a cultivator. The cultivator awoke. The butterfly has been confused ever since. Relatable.",
    "I have met immortals. They are mostly tired. I have met mortals. They are mostly hurrying. The difference is the tiring comes sooner for mortals.",
    "Today's weather is auspicious. Yesterday's was also auspicious. Tomorrow will probably be auspicious. Auspiciousness has inflated dramatically.",
    "The spirit beast you keep notes your energy. It has opinions. It is choosing not to share them. This is wisdom your spirit beast has mastered.",
    "I knew a cultivator who asked too many questions. He eventually became the answer. I would prefer you not become an answer.",
    "The stars have aligned. They align about once a month. Make of this what you will, but do not make of it more than it is.",
    "Somewhere an ancient artifact has just been unsealed. Someone is about to make a serious mistake. I am glad it is not me.",
    "The path of the sword is direct. The path of the spirit is winding. The path of the merchant leads to somewhere with a comfortable chair.",
    "Your sect's legacy weighs upon you. This is appropriate. Legacy is supposed to be heavy. If it were light, anyone could carry it.",
    "A thousand years of cultivation history fits into one observation: everyone thought they were special, and some of them were right.",
    "The rare treasure you seek is likely in the most dangerous place possible. This is a universal law of cultivation I have tested extensively.",
    "I could tell you your fortune. I will tell you instead: the fortune is not the point. The path to it is. Now you are telling me you knew that already? Then why did you ask?",
    "The old formation stone near the eastern gate hums on new moon nights. Nobody knows why. I know why. I am not telling.",
    "Cloud patterns today suggest incoming difficulty followed by a moderate breakthrough followed by exhaustion and tea. Standard.",
    "My cultivation realm is beyond your current comprehension. This is not meant as an insult. It is stated as a navigational fact.",
    "Before enlightenment: carry water, chop wood, ask questions. After enlightenment: carry water, chop wood, stop asking questions.",
    "Your pet grows alongside you. This is either heartwarming or evidence that pets absorb their owner's energy. Possibly both.",
    "The heavenly tribulation comes for all who reach sufficient power. This is the universe's quality control mechanism.",
    "I once asked the sky for answers. The sky replied with rain. I took this as a no. The sky may have had other intentions.",
    "All rivers return to the sea. All cultivators eventually stop asking me things. I live for that distant horizon.",
  ],

  ru: [
    // Лень и созерцание
    "Я собирался ответить на ваш вопрос, но дрёма показалась более продуктивной. Дрёма оказалась права.",
    "Дао Лени учит: в сомнении — отдыхай. Я сомневаюсь вот уже сорок лет. Всё ещё отдыхаю.",
    "Ваш вопрос застал меня в середине сна. Сон содержал ответы получше. К сожалению, я их забыл.",
    "Культивация утомляет. Отвечать на вопросы о культивации утомляет ЕЩЁ БОЛЬШЕ. Я возмущён вашим визитом.",
    "Мудрый культиватор бережёт энергию. Отвечать вам обошлось бы именно в ту энергию, которой мне хватает не отвечать.",
    "Я мирно спал, когда прибыл ваш вопрос. Покой покинул меня. Ваш — тоже может.",
    "Великие мастера проводили десятилетия в безмолвном уединении. Вероятно, они просто избегали таких вопросов, как ваш.",
    "Каждое слово стоит мне духовной энергии. Вы дорого мне обошлись. Надеюсь, вы довольны.",
    "Мой учитель говорил: думай прежде чем говорить. Я думал над вашим вопросом шесть часов. Ещё думаю.",
    "У меня строгое расписание: дремота, культивация, снова дремота, изредка раздача мудрости. Вы прервали дремоту.",
    "Космос необъятен, а ваш вопрос ничтожен. Оба факта раздражают меня по разным причинам.",
    "Между вашим вопросом и тишиной тишина, как правило, мудрее. Продемонстрирую — почти промолчав об этом.",
    "Основатель нашей секты достиг просветления за сорок лет абсолютного ничегонеделания. Я следую его примеру.",
    "Гора не отвечает каждому облаку, что проплывает мимо. Я стремлюсь быть больше похожим на гору.",
    "Я ответил на десять тысяч вопросов. Каждый следующий делал меня чуть более усталым, чем предыдущий.",
    "Рассмотрим такой вариант: что если ответ на ваш вопрос — просто 'идите поспите'? Я обнаружил, что это решает большинство проблем.",
    "Просветление обретается теми, кто готов к нему. Готовность означает принятие своей неготовности. Это парадокс.",
    "Сон — высшая форма культивации. Беседа — низшая. Отсюда и моя сдержанность.",
    "Мир продолжит вращаться, отвечу я или нет. Я проверил эту гипотезу неоднократно.",

    // Культивация
    "Ваша культивация {stage} намекает на потенциал. Станет ли что-то с этим потенциалом — уже не моя забота.",
    "Путь вперёд ясен. Путь требует усилий. Вы не думали о пути с меньшими усилиями?",
    "Ваша аура сегодня сильна. Ваши вопросы сегодня — не сильны. Здесь есть дисбаланс.",
    "Каждый уровень культивации открывает новые двери. Большинство дверей ведут к ещё большей работе. Я перестал открывать двери.",
    "Ци течёт туда, куда ведёт намерение. Ваше намерение, кажется, ведёт к тому, чтобы задавать мне вопросы. Ци растеряна.",
    "Прорыв требует жертв. В частности — жертвы удобной ложью о том, что всё и так хорошо.",
    "Высшие уровни культивации шепчут тем, кто слушает. Я слушаю. Слышу в основном ветер и собственное дыхание.",
    "Ваши духовные корни подают надежды. Ваше терпение — меньше. Эти вещи связаны.",
    "Я культивирую уже столетие. За это время я познал три истины. Две из них я регулярно забываю.",
    "Золотое ядро внутри вас гудит потенциалом. Постарайтесь его не уронить.",
    "Меридианы открываются один за другим. Ваши, кажется, открываются. Скоро будет больно. Готовьтесь философски.",
    "Истинный враг культиватора — не монстры, не соперничающие секты. Это голос, говорящий 'на сегодня достаточно'. Этот голос весьма мудр.",

    // Золото и ресурсы
    "Золото — язык смертных и смех культиваторов. Вы сейчас говорите и смеётесь очень тихо.",
    "Духовные камни накапливаются у тех, кто их не тратит. Это мудрость, которую вы, судя по всему, активно проверяете.",
    "Богатство не важно для просветлённых. Однако определённый объём не-важности требует определённого объёма богатства как основы.",
    "Ресурсы текут к тем, у кого пустые руки. Сначала наполните руки, потом медленно раскрывайте их. Держите открытыми. Теперь закрывайте. У вас ресурсы.",

    // Судьба и путь
    "Путь судьбы {fatePath}. Это было записано до вашего рождения, чернилами с лёгким запахом небесной иронии.",
    "Небеса выбрали ваш путь. Вы по нему идёте. Правильно ли идёте — личное развлечение вселенной.",
    "Читая судьбы многих, скажу: ваша интереснее большинства. Это не обязательно хорошая новость.",
    "Судьба — река, настаивающая на том, чтобы в ней плавали. Течение {fatePath} глубоко в вас.",
    "Карма записывает все долги, все заслуги и все особенно впечатляющие провалы. Ваша страница насыщена.",
    "Небесная книга записывает всё. Ваш раздел, судя по ощущениям, потребует расширения.",

    // НПС и память
    "Я чувствую присутствие других в вашем путешествии. Некоторые оставили впечатления. Одно всё ещё угасает.",
    "Те, кто пересекает ваш путь — не случайность. Вселенная организовала эти встречи. У вселенной, видимо, есть типаж.",
    "Ваш дух несёт эхо прошлых встреч. Эхо начинает переговариваться между собой.",

    // Мудрость
    "Скажу вам однажды, нехотя: ответ был внутри вас всё это время. Кажется очевидным теперь, когда я это сказал. Пожалуйста.",
    "То, с чем вы боретесь — я тоже с этим боролся. В конце концов я прекратил борьбу и поспал. Борьба осталась. Сон был прекрасен.",
    "В том, что вы переживаете, есть урок. Я не скажу вам какой. Найти его самостоятельно и есть урок.",
    "Вы пришли за мудростью. Я дал вам своё присутствие. В терминах культивации это эквивалентно.",
    "Упорство в культивации необходимо. Так же необходимо умение остановиться и переоценить всё. Вы не остановились. Переоцените.",
    "Труднейшие уроки — те, что жизнь преподаёт без спроса. Вы сейчас записаны на несколько таких курсов.",
    "Некоторые истины можно понять только прожив их. Эта истина, к несчастью, из таких.",
    "Путь культивации — не о том, чтобы стать сильным. О том, чтобы стать более собой. Сила — побочный эффект.",

    // Философия и мир
    "Великие секты поднимаются и падают как приливы. Горы не беспокоятся о приливах. Я стремлюсь быть горой.",
    "Где-то в мире культиватор только что прорвался на новый уровень. Где-то другой уснул прямо во время прорыва. Баланс.",
    "Десять тысяч вещей — выражения единого принципа. Я всё ещё выясняю, что это за принцип. Ещё лет сорок, наверное.",
    "История в культивации повторяется: сильная секта поднимается, расслабляется, засыпает, уступает место более голодной.",
    "Время странно движется на высоком уровне культивации. Год ощущается как день. Плохой вопрос — как столетие.",
    "Великое Дао течёт сквозь всё. Сквозь вас. Сквозь меня. Сквозь камень, на котором я сижу. Камень, возможно, опережает нас обоих.",
    "Техника важна. Но сердце важнее. И сон важнее того и другого — по моему опыту.",
    "Перед просветлением: носи воду, руби дрова, задавай вопросы. После просветления: носи воду, руби дрова, перестань задавать вопросы.",
    "Тысяча лет истории культивации вмещается в одно наблюдение: все считали себя особенными, и некоторые были правы.",
    "Редкое сокровище, которое вы ищете, скорее всего в самом опасном месте. Это универсальный закон культивации, проверенный мной неоднократно.",
    "Мой уровень культивации за пределами вашего нынешнего понимания. Это не оскорбление. Это навигационный факт.",
    "Ваш питомец растёт вместе с вами. Это либо трогательно, либо доказательство того, что питомцы поглощают энергию хозяев. Вероятно, и то, и другое.",
    "Небесное испытание приходит ко всем, достигшим достаточной силы. Это механизм контроля качества вселенной.",
    "Все реки возвращаются в море. Все культиваторы в итоге перестают меня спрашивать. Я живу этим далёким горизонтом.",
    "Духовное загрязнение накапливается там, где много конфликтов. Вот почему я предпочитаю очень тихие места. Очень. Тихие.",
    "Сеть нефритовой связи переполнена слухами сегодня. Либо кто-то совершил прорыв, либо произошло нечто ужасное. Обычно второе.",
    "Ваша карма сегодня как погода: переменная облачность с прояснениями ближе к вечеру.",
  ],

  zh: [
    // 懒惰与冥想
    "我本想回答你的问题，但小憩看起来更有成效。小憩是对的。",
    "懒惰之道教导：有疑时，休息。我已疑惑四十年，仍在休息。",
    "你的问题在我梦中传来，梦里有更好的答案，可惜我忘了。",
    "修炼本已疲惫，回答关于修炼的问题更加疲惫。我为此怨你。",
    "智者节省精力。回答你的代价，恰好等于我不回答你所需的精力。",
    "我在静静安睡，你的问题到来，平静离我而去，也许也会离你而去。",
    "古代大师在无声中闭关数十年，他们大概只是在躲避像你这样的问题。",
    "我的门派创始人通过四十年什么都不做而获得了开悟。我在效仿他。",
    "高山不回应每一朵飘过的云，我以高山为榜样。",
    "我这一生回答了一万个问题，每一个都比上一个更令我疲惫。",
    "安静说话，我现在非常安静，你正在听到答案。",
    "在你的问题和沉默之间，沉默通常更明智。我即将通过近乎沉默来示范。",

    // 修炼
    "你的{stage}修为暗示着潜力，这潜力能否发挥，幸好不是我的问题。",
    "前路清晰，前路需要努力，你可曾考虑过一条需要较少努力的路？",
    "你的气场今日强盛，你的问题今日不够强，这里有失衡需要处理。",
    "每个修炼层次都会开启新的门，大多数门通向更多的工作，我很久前就停止开门了。",
    "气随意念流动，你的意念似乎引领你来问我问题，气感到困惑了。",
    "突破需要牺牲，具体来说，是牺牲'现状已经足够好'这个舒适谎言。",
    "你的精神之根颇有前途，你的耐心就不那么有前途了，二者相互关联。",
    "金丹在你体内嗡嗡作响，充满潜力，尽量别把它摔了。",
    "经脉须逐一打开，你的经脉似乎正在打开，这迟早会很痛，做好哲学上的准备。",
    "修炼者真正的敌人不是妖兽，不是对立门派，而是那个说'今天就这样吧'的声音，那声音相当有智慧。",

    // 黄金与资源
    "黄金是凡人的语言，也是修炼者的笑话，你目前说得和笑得都很小声。",
    "灵石积累于那些不花掉它们的人手中，这是你似乎正在大量检验的智慧。",
    "财富对开悟者无所谓，然而，一定量的无所谓需要一定量的财富作为基础。",
    "资源流向双手空空之人，先填满你的手，再慢慢张开，保持张开，现在合拢，你有资源了。",

    // 命运
    "命运之路：{fatePath}。这在你出生前就已写就，墨水带着天机讽刺的淡淡气息。",
    "天道选择了你的道途，你走在其上，是否走对了是宇宙的私人娱乐。",
    "读过许多命运，你的比大多数更有趣，这不一定是好消息。",
    "命运是一条坚持要你在其中游泳的河流，{fatePath}之流在你内心流淌甚深。",
    "天机账簿记录一切业力，一切功德，以及一切特别壮观的失败，你的页面相当饱满。",

    // 智慧与哲理
    "我将不情愿地告诉你一次：答案始终在你内心，听我说出来似乎很显然，不客气。",
    "你正在挣扎的事——我也曾挣扎过，最终我停止挣扎，小憩了一觉，挣扎还在，小憩很美妙。",
    "你所经历的事中有一课，我不告诉你是什么课，自己去找就是这课。",
    "你来寻求智慧，我给了你我的存在，在修炼用语中这是等价的。",
    "坚持修炼至关重要，知道何时停下来重新评估也同样重要，你还没停下，重新评估吧。",
    "最难的课是生活不经询问就教给你的，你目前报了好几门这样的课。",
    "修炼之路不在于变得强大，在于更完整地成为自己，力量是副产品。",
    "顿悟之前：担水砍柴问问题，顿悟之后：担水砍柴停止问问题。",
    "千年修炼史可浓缩为一个观察：所有人都认为自己是特别的，其中有些人是对的。",
    "你寻找的稀有宝物很可能在最危险的地方，这是我反复验证的修炼宇宙定律。",

    // 世界与宇宙
    "大宗门如潮水般兴衰，高山不在意潮水，我以高山为志。",
    "世间某处一名修炼者刚刚突破新境，另一处某人在突破途中睡着了，平衡。",
    "万事万物皆是单一原则的表达，我仍在弄清楚那原则是什么，也许还需四十年。",
    "时间在高层修炼中奇异流动，一年如一日，一个坏问题如一个世纪。",
    "大道流经万物，流经你，流经我，流经我坐着的这块石头，石头或许走在我们前面。",
    "技巧重要，但心境更重要，而睡眠比两者都重要——这是我的经验。",
    "你的灵宠与你一同成长，这要么令人感动，要么证明灵宠会吸收主人的能量，两者皆有可能。",
    "一切河流终归大海，一切修炼者最终停止向我发问，我活在那遥远的地平线上。",
  ],
};

// ── NPC dialogue responses ───────────────────────────────────────────────────
export const NPC_RESPONSES: Record<Locale, string[]> = {
  en: [
    "Ah, {heroName}. We meet again, as fate demands. Your {stage} cultivation grows… tolerable.",
    "I've watched you from afar, {heroName}. The {fatePath} path suits you, though you'd never admit it.",
    "*notices {heroName}* You again? The cosmos truly has a cruel sense of humour. Also, well met.",
    "{heroName}. I have not forgotten our last encounter. The {relationship} between us has deepened — for better or worse.",
    "Your aura speaks of a {fatePath} cultivator. Interesting. Last time we met you were far less… whatever this is.",
    "Cultivator {heroName}! Word of your deeds has spread even to these remote paths. I will pretend I am not impressed.",
    "They say the {fatePath} path leads to ruin. They said the same about my path. We are both still here.",
    "I sense your {stage} cultivation from ten li away. You are getting stronger. This pleases me, professionally.",
    "*bows with precisely calibrated respect* Your progress is noted, {heroName}. As are your continued poor life choices.",
    "You again, {heroName}. I had prepared for a peaceful day. I should have known better.",
    "The sect elders speak of you, {heroName}. What they say depends heavily on which elder you ask.",
    "I crossed half the cultivation world to be here today. You look like you rolled out of a meditation mat. Life is unfair.",
    "Your {stage} cultivation is impressive for your age. I have reached my {stage} faster. I mention this for no particular reason.",
    "Interesting. Your spiritual pressure has changed since we last met. The change is… notable.",
    "I had heard rumours of a lazy {fatePath} cultivator making unexpected progress. I presumed the rumours exaggerated. I now presume less.",
    "Fate is a strange thing, {heroName}. It keeps arranging for us to occupy the same mountain. I have stopped questioning it.",
    "Your reputation precedes you by approximately three li. It is a colourful reputation.",
    "We cultivators are all on the same path, ultimately. Some of us are further along. Most of us are not telling which.",
    "I once thought the {fatePath} path was a dead end. You seem determined to prove otherwise. Against my predictions.",
    "*nods grudgingly* I have revised my assessment of you, {heroName}. Upward. Slightly. Do not let it go to your head.",
    "They call this a chance meeting. I call this the fourteenth chance meeting in six months. Fate is persistent.",
    "Your spiritual beast looks well. Mine looks better. I say this with absolute neutrality.",
    "The mountain path is dangerous today. You seem fine. Either you are stronger than I thought, or the mountain path is aware of your reputation.",
    "You carry {stage} power lightly, {heroName}. Most at your level walk differently. You walk like someone who hasn't quite noticed.",
    "I heard about your dungeon run. The stories already contradict each other, which is usually a sign it went interestingly.",
    "Rumour has it you bested a {stage} beast recently. Rumour also exaggerates. I look forward to hearing the real count.",
    "Your {relationship} energy precedes our meeting. The air around you has a certain quality that says: we have history.",
    "I am on a mission of great importance today. Your presence here is either coincidence or the universe being subtle. Neither surprises me.",
    "The jade tokens are active today — old formations stirring. Dangerous times for those who don't pay attention. You have been warned.",
    "Cultivator. Your path has crossed mine {encounterCount} times now. I have started keeping count. I recommend you do the same.",
  ],
  ru: [
    "А, {heroName}. Встречаемся снова, как требует судьба. Ваша культивация {stage} становится… терпимой.",
    "Я наблюдал за вами издали, {heroName}. Путь {fatePath} вам подходит, хоть вы никогда не признаете.",
    "*замечает {heroName}* Снова вы? У космоса поистине жестокое чувство юмора. Рад встрече.",
    "{heroName}. Я не забыл нашу последнюю встречу. Наши {relationship} углубились — к добру или нет.",
    "Ваша аура говорит о культиваторе пути {fatePath}. Интересно. В прошлый раз, когда мы встречались, вы были куда менее… всем этим.",
    "Культиватор {heroName}! Слухи о ваших подвигах дошли даже до этих отдалённых троп. Притворяюсь, что не впечатлён.",
    "Говорят, путь {fatePath} ведёт к гибели. То же самое говорили о моём пути. Мы оба всё ещё здесь.",
    "Я чую вашу культивацию {stage} за десять ли. Вы становитесь сильнее. В профессиональном смысле меня это радует.",
    "*кланяется с точно выверенным уважением* Ваш прогресс отмечен, {heroName}. Как и ваш продолжающийся выбор сомнительных решений.",
    "Снова вы, {heroName}. Я готовился к спокойному дню. Следовало ожидать.",
    "Старейшины секты говорят о вас, {heroName}. Что именно — зависит от того, какого старейшины спросить.",
    "Ваша культивация {stage} впечатляет для вашего возраста. Я достиг своей {stage} быстрее. Упоминаю это без какой-либо особой причины.",
    "Интересно. Ваше духовное давление изменилось с нашей последней встречи. Изменение… примечательное.",
    "Судьба странная вещь, {heroName}. Она постоянно устраивает нам встречи на одной горе. Я перестал это оспаривать.",
    "Ваша репутация опережает вас примерно на три ли. Это красочная репутация.",
    "Я пересёк полмира культивации, чтобы оказаться здесь. Вы выглядите так, будто только что выкатились с медитационного коврика. Жизнь несправедлива.",
    "Говорят, это случайная встреча. Я называю это четырнадцатой случайной встречей за шесть месяцев. Судьба настойчива.",
    "Ваша духовная зверюга выглядит хорошо. Моя выглядит лучше. Говорю это с абсолютным нейтралитетом.",
    "*нехотя кивает* Я пересмотрел свою оценку вас, {heroName}. В сторону повышения. Незначительно. Не позвольте этому вскружить вам голову.",
    "Слышал о вашем забеге в подземелье. Истории уже противоречат друг другу, что обычно означает: всё прошло интересно.",
  ],
  zh: [
    "啊，{heroName}，天命使然，我们再度相逢，你的{stage}修为……勉强能看了。",
    "我一直在远处观察你，{heroName}，{fatePath}之道适合你，尽管你永远不会承认。",
    "*注意到{heroName}* 又是你？天道的幽默感真残忍，幸会。",
    "{heroName}，我没忘上次的相遇，我们之间的{relationship}已加深——不管是好是坏。",
    "你的气息透露出一位{fatePath}修炼者，有意思，上次见面时你远不如现在这般……这样。",
    "修炼者{heroName}！你的事迹连这偏远之地都有耳闻，我假装没被打动。",
    "他们说{fatePath}之路通向毁灭，他们也这样说过我的路，我们都还在这里。",
    "我在十里之外便感受到你的{stage}修为，你在变强，从职业角度来说这让我欣慰。",
    "*以精确拿捏的礼节鞠躬* 你的进步已被记下，{heroName}，你持续糟糕的人生选择也同样被记下了。",
    "又是你，{heroName}，我本以为今天会是平静的一天，早该料到了。",
    "宗门长老们谈论你，{heroName}，具体说什么取决于你问哪位长老。",
    "命运是件奇怪的事，{heroName}，它不断安排我们出现在同一座山上，我已停止追问原因。",
    "你的名声比你提前大约三里到来，那是一段丰富多彩的名声。",
    "*勉强点头* 我修正了对你的评价，{heroName}，上调了，略微上调，别让这冲昏你的头脑。",
    "他们说这是偶遇，我称之为六个月内的第十四次偶遇，命运执着得很。",
    "修炼者，你的道途与我的交叉了{encounterCount}次，我已开始计数，建议你也这样做。",
  ],
};
